---
pilot:
  resources:
    requests:
      cpu: 10m
      memory: 100Mi
  cni:
    enabled: true

global:
  proxy:
    # resource limits for the sidecar
    resources:
      requests:
        cpu: 10m
        memory: 40Mi

