---
version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...
    # - go fmt ./...
    # - go vet ./...
    # - go test ./...

builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/main.go
    binary: istio-fortsa
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.Version={{ .Version }} -X main.Commit={{ .Commit }} -X main.CommitDate={{ .CommitDate }}
    goos:
      - linux
    goarch:
      - amd64

kos:
  - base_image: gcr.io/distroless/static:nonroot
    tags:
      - "{{ .Tag }}"
      - latest
    platforms:
      - linux/amd64
      - linux/arm64
    main: ./cmd
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
      - -extldflags "-static"
      - -X main.Version={{ .Version }}
      - -X main.Commit={{ .Commit }}
      - -X main.CommitDate={{ .CommitDate }}
    bare: true
    preserve_import_paths: false
    base_import_paths: false

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs"
      - "^test"
      - "^chore"
      - "Merge pull request"
      - "Merge branch"
