apiVersion: v1
kind: Service
metadata:
  name: {{ include "istio-fortsa.fullname" . }}-cm-metrics-svc
  labels:
    control-plane: controller-manager
  {{- include "istio-fortsa.labels" . | nindent 4 }}
spec:
  type: {{ .Values.cmMetricsSvc.type }}
  selector:
    control-plane: controller-manager
  {{- include "istio-fortsa.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.cmMetricsSvc.ports | toYaml | nindent 2 }}