apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "istio-fortsa.fullname" . }}-manager-role
  labels:
  {{- include "istio-fortsa.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - mutatingwebhookconfigurations
  - namespaces
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - mutatingwebhookconfigurations/finalizers
  - namespaces/finalizers
  - pods/finalizers
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - mutatingwebhookconfigurations/status
  - namespaces/status
  - pods/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "istio-fortsa.fullname" . }}-manager-rolebinding
  labels:
  {{- include "istio-fortsa.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "istio-fortsa.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "istio-fortsa.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'