apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "istio-fortsa.fullname" . }}-controller-manager
  labels:
  {{- include "istio-fortsa.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.controllerManager.serviceAccount.annotations | nindent 4 }}