---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  - pods/portforward
  - serviceaccounts/token
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - namespaces
  - namespaces/finalizers
  - namespaces/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  - pods/finalizers
  - pods/status
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  - mutatingwebhookconfigurations/finalizers
  - mutatingwebhookconfigurations/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - daemonset
  - deployment
  - replicaset
  - statefulset
  verbs:
  - get
  - list
  - patch
  - update
  - watch
