apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: istio-fortsa.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: Update istio proxies automatically
  displayName: istio-fortsa
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - istio
  links:
  - name: Istio Fortsa
    url: https://istio-fortsa.domain
  maturity: alpha
  minKubeVersion: 1.24.0
  provider:
    name: istio-fortsa
  version: 0.0.0
