---
name: "Release"

on:
  release:

permissions:
  contents: write
  packages: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      #- name: Set up Go
      #  uses: actions/setup-go@v5
      #  with:
      #    go-version: stable

      - name: Build and Push Docker Images
        run: make docker-buildx VERSION=${{ github.event.release.tag_name }}
      
      - name: Build and Push OLM Bundle Image
        run: make bundle-push VERSION=${{ github.event.release.tag_name }}

      - name: Build and Push OLM Catalog Image
        run: make catalog-push VERSION=${{ github.event.release.tag_name }}
